version: "3.9"

services:
  ib-gateway:
    image: waytrade/ib-gateway:1010
    restart: unless-stopped
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-live}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
    ports:
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:4002:4002"
      - "0.0.0.0:5900:5900"
    networks:
      - main
  app:
    build: .
    environment:
      - IB_GATEWAY_HOST=ib-gateway
      - IB_GATEWAY_PORT=4001
    networks:
      - main

networks:
  main:
    name: main
    
#     docker run -d \
# --env IB_ACCOUNT= \ #YOUR_USER_ID 
# --env IB_PASSWORD= \ #YOUR_PASSWORD  
# --env TRADE_MODE= \ #paper or live 
# --p 4002:4002 \ #brige IB gateway port to your local port 4002
# manhinhang/ib-gateway-docker tail -f /dev/null